Feature/add devise
pavl1n/Flunky pull request #8
Opened 2021-04-12 16:55 UTC by pavl1n

2021-04-13 17:44 UTC, TanyaAkulich requested changes

2021-04-13 17:44 UTC, TanyaAkulich commented on db/migrate/20210402074115_create_users.rb
> +      t.string :phone_number
you can't change existen migrations

2021-04-13 17:44 UTC, TanyaAkulich commented on config/routes.rb
> +  root to: 'users#profile'
in other pr you have an another root

2021-04-13 17:44 UTC, TanyaAkulich commented on db/migrate/20210412091412_add_devise_to_users.rb
> +      t.string :email,              null: false, default: ""
recheck this migration and remove unnecessary stuff

2021-04-15 12:55 UTC, TanyaAkulich requested changes

2021-04-15 12:55 UTC, TanyaAkulich commented on db/migrate/20210412091412_add_devise_to_users.rb
> +    add_index :users, :reset_password_token, unique: true
why do you need indexes on these tokens

2021-04-15 12:55 UTC, TanyaAkulich commented on app/views/devise/shared/_links.html.slim
> +  = link_to "Log in", new_session_path(resource_name)
use i18n

2021-04-15 12:55 UTC, TanyaAkulich commented on app/views/devise/sessions/new.html.slim
> +    = f.submit "Log in"
single quotes

2021-04-15 12:55 UTC, TanyaAkulich commented on app/views/devise/registrations/edit.html.slim
> +      | (leave blank if you don't want to change it)
recheck your views

2021-04-19 09:40 UTC, TanyaAkulich requested changes

2021-04-19 09:40 UTC, TanyaAkulich commented on app/controllers/after_signup_controller.rb
> +    @user = current_user
current_user is visible in views

2021-04-19 09:40 UTC, TanyaAkulich commented on app/controllers/phone_verifications_controller.rb
> +      country_code: '+375',
to conts

2021-04-20 07:14 UTC, TanyaAkulich requested changes

2021-04-20 07:14 UTC, TanyaAkulich commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
do we need database_authenticatable?

2021-04-20 07:14 UTC, TanyaAkulich commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
recoverable

2021-04-20 07:14 UTC, TanyaAkulich commented on app/models/user.rb
> +  devise :database_authenticatable, :registerable,
validatable

2021-04-20 07:14 UTC, TanyaAkulich commented on app/models/user.rb
> +  def email_required?
remove

2021-04-20 07:14 UTC, TanyaAkulich commented on app/models/user.rb
> +  def email_required?
devise/registration_controller

```
def initialize
  super
  your stuff here
end

```

2021-04-20 07:14 UTC, TanyaAkulich commented on config/locales/devise.en.yml
> +en:
t.i18n('devise.confirmation.send_instructions')

2021-04-21 09:54 UTC, pavl1n commented on app/models/user.rb
> +    where(phone_number: conditions[:phone_number]).first || where(email: conditions[:email]).first || where(reset_password_token: conditions[:reset_password_token]).first
how this could be rewritten so that hound doesn't swear about length

2021-04-22 07:55 UTC, TanyaAkulich requested changes

2021-04-22 07:55 UTC, TanyaAkulich commented on app/controllers/phone_verifications_controller.rb
> +      country_code: PHONE_CODE,
add validation if you want to use belarus code only or parse numbers to extracts codes

2021-04-22 07:55 UTC, TanyaAkulich commented on app/controllers/application_controller.rb
> +  before_action :configure_permitted_parameters, if: :devise_controller?
move it to devise controller

2021-04-22 07:55 UTC, TanyaAkulich commented on app/controllers/registrations_controller.rb
> +    current_user.update(user_type: 1)
rename controller if it's for clients registration only

2021-04-22 07:55 UTC, TanyaAkulich commented on app/helpers/registrations_helper.rb
> +module RegistrationsHelper
remove useless files

2021-04-22 07:55 UTC, TanyaAkulich commented on config/routes.rb
>    root 'menu#index'
move root on the top of this file

2021-04-22 07:55 UTC, TanyaAkulich commented on config/routes.rb
> +  match "/404", :to => "errors#not_found", :via => :all
old syntacsis

2021-04-22 07:55 UTC, TanyaAkulich commented on db/migrate/20210412091412_add_devise_to_users.rb
> +      t.string :email,              null: false, default: ""
add uniquess validation for db

2021-04-24 08:37 UTC, TanyaAkulich requested changes

2021-04-24 08:37 UTC, TanyaAkulich commented on app/controllers/phone_verifications_controller.rb
> +require_relative '../lib/constants'
1. it's not working
2. use module in incude it everywhere you need a conts

2021-04-24 08:37 UTC, TanyaAkulich commented on config/routes.rb
> +  match "/404", to: "errors#not_found", via: :all
single quotes

2021-04-27 09:09 UTC, TanyaAkulich approved these changes

2021-04-27 16:15 UTC, merged